// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmAction(arg1, arg2) {
  return window['go']['main']['App']['ConfirmAction'](arg1, arg2);
}

export function DeleteOrganization(arg1) {
  return window['go']['main']['App']['DeleteOrganization'](arg1);
}

export function DeleteProject(arg1, arg2) {
  return window['go']['main']['App']['DeleteProject'](arg1, arg2);
}

export function ExportCSVByMonth(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportCSVByMonth'](arg1, arg2, arg3);
}

export function ExportCSVByYear(arg1, arg2) {
  return window['go']['main']['App']['ExportCSVByYear'](arg1, arg2);
}

export function GetMonthlyWorkTime(arg1, arg2) {
  return window['go']['main']['App']['GetMonthlyWorkTime'](arg1, arg2);
}

export function GetMonthlyWorktimeByProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMonthlyWorktimeByProject'](arg1, arg2, arg3);
}

export function GetOrganizations() {
  return window['go']['main']['App']['GetOrganizations']();
}

export function GetProjects(arg1) {
  return window['go']['main']['App']['GetProjects'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWeeklyWorkTime(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetWeeklyWorkTime'](arg1, arg2, arg3);
}

export function GetWorkTime(arg1, arg2) {
  return window['go']['main']['App']['GetWorkTime'](arg1, arg2);
}

export function GetWorkTimeByProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetWorkTimeByProject'](arg1, arg2, arg3);
}

export function GetYearlyWorkTime(arg1, arg2) {
  return window['go']['main']['App']['GetYearlyWorkTime'](arg1, arg2);
}

export function GetYearlyWorkTimeByProject(arg1, arg2) {
  return window['go']['main']['App']['GetYearlyWorkTimeByProject'](arg1, arg2);
}

export function MonitorTime() {
  return window['go']['main']['App']['MonitorTime']();
}

export function NewOrganization(arg1, arg2) {
  return window['go']['main']['App']['NewOrganization'](arg1, arg2);
}

export function NewProject(arg1, arg2) {
  return window['go']['main']['App']['NewProject'](arg1, arg2);
}

export function RenameOrganization(arg1, arg2) {
  return window['go']['main']['App']['RenameOrganization'](arg1, arg2);
}

export function RenameProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2, arg3);
}

export function SetOrganization(arg1, arg2) {
  return window['go']['main']['App']['SetOrganization'](arg1, arg2);
}

export function SetProject(arg1) {
  return window['go']['main']['App']['SetProject'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartTimer(arg1, arg2) {
  return window['go']['main']['App']['StartTimer'](arg1, arg2);
}

export function StopTimer(arg1, arg2) {
  return window['go']['main']['App']['StopTimer'](arg1, arg2);
}

export function TimeElapsed() {
  return window['go']['main']['App']['TimeElapsed']();
}

export function UpdateAvailable() {
  return window['go']['main']['App']['UpdateAvailable']();
}
