name: Build & Publish

on:
  push:
    tags:
    # Match any new tag
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: go-work-tracker, platform: linux/amd64, os: ubuntu-latest},
          {name: go-work-tracker, platform: windows/amd64, os: windows-latest},
          {name: go-work-tracker, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build & Publish
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: '1.21'
          node-version: '20'
          nsis: true
