name: Build & Publish

on:
  push:
    tags:
    # Match any new tag
      - 'v*'

env:
  APP_ENV: production

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: go-work-tracker, platform: linux/amd64, os: ubuntu-latest, nsis: true},
          {name: go-work-tracker, platform: windows/amd64, os: windows-latest, nsis: true},
          {name: go-work-tracker, platform: windows/amd64, os: windows-latest, nsis: false},
          {name: go-work-tracker, platform: darwin/universal, os: macos-latest, nsis: true}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Extract version from tag
        id: version
        shell: bash
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Update wails.json
        shell: bash
        run: node build/updateConfig.cjs ${{ env.version }}
      - name: Setup GoLang
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
        shell: bash
      - name: Build App
        run: wails build --platform ${{ matrix.build.platform }} -o ${{ matrix.build.name }} -nsis ${{ matrix.build.nsis }}
        shell: bash
        env:
          APP_ENV: production
          APP_VERSION: ${{ env.version }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{runner.os}}-${{ matrix.build.name }}
          path: |
            ./build/bin/*
