name: Build & Publish

on:
  push:
    tags:
    # Match any new tag
      - 'v*'

env:
  APP_ENV: production

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: go-work-tracker, platform: linux/amd64, os: ubuntu-latest, nsis: true},
          {name: go-work-tracker, platform: windows/amd64, os: windows-latest, nsis: true},
          {name: go-work-tracker, platform: windows/amd64, os: windows-latest, nsis: false},
          {name: go-work-tracker, platform: darwin/universal, os: macos-latest, nsis: true}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Update wails.json
        run: node build/updateConfig.cjs ${{ GITHUB_REF#refs/tags/ }}
      - name: Build & Publish
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: '1.21'
          node-version: '20'
          nsis: ${{ matrix.build.nsis }}
        env:
          APP_ENV: production
          APP_VERSION: ${{ GITHUB_REF#refs/tags/ }}
