name: Build & Publish

on:
  push:
    tags:
    # Match any new tag
      - 'v*'

env:
  APP_ENV: production

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: go-work-tracker, platform: linux/amd64, os: ubuntu-latest, nsis: true},
          {name: go-work-tracker, platform: windows/amd64, os: windows-latest, nsis: true},
          {name: go-work-tracker, platform: windows/amd64, os: windows-latest, nsis: false},
          {name: go-work-tracker, platform: darwin/universal, os: macos-latest, nsis: true}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Extract version from tag
        id: version
        shell: bash
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Update wails.json
        shell: bash
        run: node build/updateConfig.cjs ${{ env.version }}
      # - name: Build & Publish
      #   uses: dAppServer/wails-build-action@v2.2
      - name: Build & Publish
        uses: actions/github-script@v5
        with:
          script: |
            // Setup and configure GoLang
            await github.run({uses: 'actions/setup-go@v4', with: {check-latest: true, go-version: '1.21'}});
            await github.exec('go version');
            // Setup and configure NodeJS
            await github.run({uses: 'actions/setup-node@v3', with: {node-version: '20'}});
            // install wails
            await github.exec('go install github.com/wailsapp/wails/v2/cmd/wails@latest');
            // Building step
            await github.exec('wails build --platform ${{ matrix.build.platform }} -o ${{ matrix.build.name }} -nsis ${{ matrix.build.nsis }}');
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: '1.21'
          node-version: '20'
          nsis: ${{ matrix.build.nsis }}
        env:
          APP_ENV: production
          APP_VERSION: ${{ env.version }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{runner.os}}-${{ matrix.build.name }
          path: |
            ./build/bin/*
